build: update golang version to 1.20
Finschia/ostracon pull request #665
Opened 2023-07-14 05:54 UTC by 0Tech

## Description

Closes: #664

2023-07-19 06:50 UTC, tnasu requested changes
Please re-check the below:
* Makefile
* REAEME.md
* test/e2e/docker/Dockerfile

2023-07-19 06:54 UTC, ulbqb commented
Please update these files.
https://github.com/Finschia/ostracon/blob/80d5dd0b2dd56f31befafa9190b706944e5224f1/README.md?plain=1#L9
https://github.com/Finschia/ostracon/blob/80d5dd0b2dd56f31befafa9190b706944e5224f1/Makefile#L261

2023-07-25 03:42 UTC, tnasu approved these changes

2023-07-25 06:22 UTC, torao approved these changes

2023-07-25 06:25 UTC, merged